### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by chritallic** [Phaiax/gtkneofix#1]
Hi, thanks for posting your gtkneofix.

I am having issues compiling it.  I followed your instructions.  First, it looks like you had git and automake missing from “needed tools” in the install section.  Second, after installing them I got the following error message:

> aclocal: installing 'm4/pkg.m4' from '/usr/share/aclocal/pkg.m4'
> configure.ac:35: error: possibly undefined macro: AC_PROG_LIBTOOL
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> autoreconf: /usr/bin/autoconf failed with exit status: 1

After running aclocal && autoreconf -i I still get:

> configure.ac:34: installing 'build-aux/ar-lib'
> configure.ac:29: installing 'build-aux/compile'
> configure.ac:25: installing 'build-aux/install-sh'
> configure.ac:25: installing 'build-aux/missing'
> Makefile.am:12: error: Libtool library used but 'LIBTOOL' is undefined
> Makefile.am:12:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
> Makefile.am:12:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
> Makefile.am:12:   If 'LT_INIT' is in 'configure.ac', make sure
> Makefile.am:12:   its definition is in aclocal's search path.
> Makefile.am: installing 'build-aux/depcomp'
> autoreconf: automake failed with exit status: 1

Would you be able to tell me how to fix this?

Many thanks in advance!

**Comment by Phaiax** [comment]
I guess I was also missing libtool as requirement. I updated the Readme. Can you check if it works now and give feedback?

**Comment by chritallic** [comment]
That was it. Worked like a charm! Thanks so much.
